Date:01.12

## some trained models:

0. default: epochs=200, batch_size=8

1. model_1: feat=100, epochs=10, batch_size=2

2. model_2: feat=100, epochs=20, batch_size=2

3. model_3: feat=100, epochs=20, batch_size=4

4. model_4: feat=100, epochs=30, batch_size=2

5. model_5: feat=80, epoch=20, batch_size=2, max_feature_dim=80, max_model_dim=80, max_num_cluster=10

6. model_6: feat=80, epoch=20, batch_size=4, max_feature_dim=80, max_model_dim=80, max_num_cluster=10

7. model_7: feat=70, epoch=20, batch_size=2, inflate_full=True, delta=0.01, max_feature_dim=70, max_model_dim=70, max_num_cluster=70

8. model_8: feat=20, epoch=20, batch_size=4, inflate_full=True, delta=0.01, max_feature_dim=20, max_model_dim=20, max_num_cluster=10

9. model_9: feat=70, epoch=20, batch_size=4, inflate_full=True, delta=0.01, max_feature_dim=70, max_model_dim=70, max_num_cluster=70

10. model_10: feat=100, epoch=20, batch_size=2, inflate_full=True, delta=0.01, max_feature_dim=100, max_model_dim=100, max_num_cluster=10

11. model_11: feat=20, epoch=20, batch_szie=4, inflate_full=True, delta=0.01, max_feature_dim=20, max_model_dim=20, max_num_cluster=30

12. model_12: feat=30, epoch=20, batch_szie=4, inflate_full=False, delta=0.01, max_feature_dim=30, max_model_dim=30, max_num_cluster=70

13. model_13: feat=20, epoch=20, batch_szie=8, inflate_full=True, delta=0.01, max_feature_dim=20, max_model_dim=20, max_num_cluster=50

14. model_14: feat=70, inflate_full=True, delta=0.01, max_feature_dim=70, max_model_dim=70, max_num_cluster=70, epochs=20, batch_size=4, seq_len=2500

15. model_15 (STOPPED at Iteration 8): feat=70, epoch=20, batch_size=8, inflate_full=True, delta=0.01, max_feature_dim=70, max_model_dim=70, max_num_cluster=70

16. model_16: feat=70, inflate_full=True, delta=0.01, max_feature_dim=70, max_model_dim=70, max_num_cluster=70, epochs=20, batch_size=4, seq_len=1000

17. model_17: feat=70, inflate_full=True, delta=0.01, max_feature_dim=70, max_model_dim=70, max_num_cluster=70, epochs=20, batch_size=8, seq_len=2500

18. model_18: SquareGMM of Simon, feat=80, inflate_full=True, delta=0.01, max_feature_dim=80, max_model_dim=80, prior.gmm.max_num_cluster=80, EPOCHS=50, BATCH_SIZE=4

19. model_19: SquareGMM of Simon, feat=80, inflate_full=True, delta=0.01, max_feature_dim=80, max_model_dim=80, prior.gmm.max_num_cluster=80, EPOCHS=50, BATCH_SIZE=8 (->STOPPED after iteration 25)

20. model_20: feat=70, inflate_full=True, delta=0.01, max_feature_dim=70, max_model_dim=70, max_num_cluster=70, epochs=50, batch_size=4  (originally test with Epochs=100, but it's broken after 50 epochs)

21. model_21: SquareGMM of Simon, feat=100, inflate_full=True, delta=0.01, max_feature_dim=100, max_model_dim=100, prior.gmm.max_num_cluster=100, EPOCHS=50, BATCH_SIZE=4

22. model_22: SquareGMM of Simon, feat=70, inflate_full=True, delta=0.01, max_feature_dim=70, max_model_dim=70, prior.gmm.max_num_cluster=70, EPOCHS=50, BATCH_SIZE=4

23. model_23: SquareGMM of Simon, feat=60, inflate_full=True, delta=0.01, max_feature_dim=60, max_model_dim=60, prior.gmm.max_num_cluster=60, EPOCHS=50, BATCH_SIZE=6

24. model_24: SquareGMM of Simon, feat=70, inflate_full=True, delta=0.01, max_feature_dim=70, max_model_dim=70, prior.gmm.max_num_cluster=70, EPOCHS=50, BATCH_SIZE=6

24.2. model_24_2: SquareGMM of Simon, feat=70, inflate_full=True, delta=0.01, max_feature_dim=70, max_model_dim=70, prior.gmm.max_num_cluster=70, EPOCHS=100, BATCH_SIZE=6

https://neptune.ai/blog/f1-score-accuracy-roc-auc-pr-auc

In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# paths of models
default_dir = "../results/adbench/context5000.feat100.R500.inf-fullFalse.LTFalse.gen1tr1True.reuse100.E200.step1000.bs8.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_1_dir = "../results/adbench/context5000.feat100.R500.inf-fullFalse.LTFalse.gen1tr1True.reuse100.E10.step1000.bs2.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_2_dir = "../results/adbench/context5000.feat100.R500.inf-fullFalse.LTFalse.gen1tr1True.reuse100.E20.step1000.bs2.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_3_dir = "../results/adbench/context5000.feat100.R500.inf-fullFalse.LTFalse.gen1tr1True.reuse100.E20.step1000.bs4.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_4_dir = "../results/adbench/context5000.feat100.R500.inf-fullFalse.LTFalse.gen1tr1True.reuse100.E30.step1000.bs2.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_5_dir = "../results/adbench/context5000.feat80.R500.inf-fullFalse.LTFalse.gen1tr1True.reuse100.E20.step1000.bs2.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_6_dir = "../results/adbench/context5000.feat80.R500.inf-fullFalse.LTFalse.gen1tr1True.reuse100.E20.step1000.bs4.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_7_dir = "../results/adbench/(Simon)context5000.feat70.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E20.step1000.bs2.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_8_dir = "../results/adbench/num_cluster_10_context5000.feat20.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E20.step1000.bs4.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_9_dir = "../results/adbench/(Simon)context5000.feat70.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E20.step1000.bs4.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_10_dir = "../results/adbench/context5000.feat100.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E20.step1000.bs2.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_11_dir = "../results/adbench/num_cluster_30_context5000.feat20.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E20.step1000.bs4.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_12_dir = "../results/adbench/(Simon)context5000.feat30.R500.inf-fullFalse.LTFalse.gen1tr1True.reuse100.E20.step1000.bs4.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_13_dir = "../results/adbench/(Simon)context5000.feat20.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E20.step1000.bs8.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_14_dir = "../results/adbench/context2500.feat70.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E20.step1000.bs4.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_15_dir = "../results/adbench/context5000.feat70.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E100.step1000.bs8.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_16_dir = "../results/adbench/context1000.feat70.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E20.step1000.bs4.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_17_dir = "../results/adbench/context2500.feat70.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E20.step1000.bs8.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_18_dir = "../results/adbench/context5000.feat80.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E50.step1000.bs4.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"

model_19_dir = "../results/adbench/context5000.feat80.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E25.step1000.bs8.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_20_dir = "../results/adbench/(GMM)context5000.feat70.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E50.step1000.bs4.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_21_dir = "../results/adbench/context5000.feat100.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E50.step1000.bs4.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"

model_22_dir = "../results/adbench/context5000.feat70.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E50.step1000.bs4.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_23_dir = "../results/adbench/context5000.feat60.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E50.step1000.bs6.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_24_dir = "../results/adbench/context5000.feat70.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E50.step1000.bs6.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_24_2_dir = "../results/adbench/context5000.feat70.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E100.step1000.bs6.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_25_dir = "../results/adbench/context5000.feat40.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E50.step1000.bs6.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"
model_26_dir = "../results/adbench/context5000.feat20.R500.inf-fullTrue.LTFalse.gen1tr1True.reuse100.E100.step1000.bs8.lr0.001.emb256.hdim512.nhead4.nlayer4.ndevice1/train_seed=0.transform=quantile.feat_truncation=subsampling"

### 0. Default model

In [3]:
default_aucroc_scores = []
default_aucpr_scores = []
default_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(default_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        default_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        default_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        default_f1_scores.append(f1)

# compute average scores of all datasets
default_avg_aucroc = sum(default_aucroc_scores) / len(default_aucroc_scores)
default_avg_aucpr = sum(default_aucpr_scores) / len(default_aucpr_scores)
default_avg_f1 = sum(default_f1_scores) / len(default_f1_scores)

print(f"number of datasets: {len(default_aucroc_scores)}")
print(f"Average aucroc: {default_avg_aucroc}")
print(f"Average aucpr: {default_avg_aucpr}")
print(f"Average f1: {default_avg_f1}")

number of datasets: 121
Average aucroc: 0.7590645511541744
Average aucpr: 0.4786638498057685
Average f1: 0.4666975187169514

#### Analyzing top 10 Datasets with the worst aucroc scores

In [4]:
default_model_dict = {'dataset': datasets_name, 'aucroc': default_aucroc_scores, 'aucpr': default_aucpr_scores, 'f1':default_f1_scores}
default_model_df = pd.DataFrame(default_model_dict)
default_model_top10_worst_aucroc = default_model_df.sort_values(by='aucroc', ascending=True).head(10)
default_model_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
113         20_letter  0.408953  0.093312  0.040000
83          36_speech  0.429277  0.029485  0.032787
53               imdb  0.446315  0.082809  0.060000
46   MNIST-C_identity  0.470528  0.087276  0.078000
92             amazon  0.496570  0.094834  0.084000
59           47_yeast  0.499131  0.509999  0.504931
23           20news_1  0.510875  0.097916  0.096000
57           20news_2  0.514481  0.100246  0.104839
22     MVTec-AD_screw  0.521039  0.431593  0.369565
58           20news_5  0.531051  0.112783  0.092105

### 1. Model_1

In [5]:
model_1_aucroc_scores = []
model_1_aucpr_scores = []
model_1_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_1_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_1_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_1_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_1_f1_scores.append(f1)

# compute average scores of all datasets
model_1_avg_aucroc = sum(model_1_aucroc_scores) / len(model_1_aucroc_scores)
model_1_avg_aucpr = sum(model_1_aucpr_scores) / len(model_1_aucpr_scores)
model_1_avg_f1 = sum(model_1_f1_scores) / len(model_1_f1_scores)

print(f"number of datasets: {len(model_1_aucroc_scores)}")
print(f"Average aucroc: {model_1_avg_aucroc}")
print(f"Average aucpr: {model_1_avg_aucpr}")
print(f"Average f1: {model_1_avg_f1}")

number of datasets: 121
Average aucroc: 0.7008943315112038
Average aucpr: 0.4009097034205178
Average f1: 0.3924483452887953

In [6]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_1_dict = {'dataset': datasets_name, 'aucroc': model_1_aucroc_scores, 'aucpr': model_1_aucpr_scores, 'f1': model_1_f1_scores}
model_1_df = pd.DataFrame(model_1_dict)
model_1_top10_worst_aucroc = model_1_df.sort_values(by='aucroc', ascending=True).head(10)
model_1_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
16            33_skin  0.143499  0.212402  0.064292
83          36_speech  0.354335  0.025251  0.049180
53               imdb  0.402843  0.074834  0.042000
113         20_letter  0.428693  0.124063  0.050000
88               yelp  0.459804  0.091014  0.080000
120            SVHN_0  0.468861  0.095078  0.100000
92             amazon  0.469754  0.093950  0.094000
46   MNIST-C_identity  0.479537  0.091474  0.094000
58           20news_5  0.484348  0.116388  0.105263
13           9_census  0.485130  0.109006  0.102870

In [7]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_1_dict = {'dataset': datasets_name, 'aucroc': model_1_aucroc_scores, 'aucpr': model_1_aucpr_scores, 'f1': model_1_f1_scores}
model_1_df = pd.DataFrame(model_1_dict)
model_1_top10_best_aucroc = model_1_df.sort_values(by='aucroc', ascending=False).head(10)
model_1_top10_best_aucroc

             dataset    aucroc     aucpr        f1
89   21_Lymphography  1.000000  1.000000  1.000000
47           43_WDBC  1.000000  1.000000  1.000000
38      15_Hepatitis  1.000000  1.000000  1.000000
119          45_wine  1.000000  1.000000  1.000000
96           16_http  0.999461  0.934203  0.928571
76        32_shuttle  0.998385  0.984586  0.977214
98          10_cover  0.991095  0.801913  0.778017
24         4_breastw  0.990946  0.980155  0.975904
5     MNIST-C_stripe  0.990279  0.936886  0.856000
114        11_donors  0.982704  0.876070  0.865887

### 2. Model_2

In [8]:
model_2_aucroc_scores = []
model_2_aucpr_scores = []
model_2_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_2_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_2_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_2_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_2_f1_scores.append(f1)

# compute average scores of all datasets
model_2_avg_aucroc = sum(model_2_aucroc_scores) / len(model_2_aucroc_scores)
model_2_avg_aucpr = sum(model_2_aucpr_scores) / len(model_2_aucpr_scores)
model_2_avg_f1 = sum(model_2_f1_scores) / len(model_2_f1_scores)

print(f"number of datasets: {len(model_2_aucroc_scores)}")
print(f"Average aucroc: {model_2_avg_aucroc}")
print(f"Average aucpr: {model_2_avg_aucpr}")
print(f"Average f1: {model_2_avg_f1}")

number of datasets: 121
Average aucroc: 0.7186872500968602
Average aucpr: 0.42481230457200025
Average f1: 0.41632704128468684

In [9]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_2_dict = {'dataset': datasets_name, 'aucroc': model_2_aucroc_scores, 'aucpr': model_2_aucpr_scores, 'f1': model_2_f1_scores}
model_2_df = pd.DataFrame(model_2_dict)
model_2_top10_worst_aucroc = model_2_df.sort_values(by='aucroc', ascending=True).head(10)
model_2_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
83          36_speech  0.397023  0.026702  0.000000
16            33_skin  0.401409  0.296046  0.229848
113         20_letter  0.433660  0.107705  0.050000
86           20news_4  0.455000  0.085336  0.073171
35         19_landsat  0.456007  0.391914  0.298575
53               imdb  0.457208  0.084075  0.058000
13           9_census  0.481458  0.117241  0.130926
80          CIFAR10_2  0.485118  0.098310  0.095057
46   MNIST-C_identity  0.498653  0.095340  0.084000
88               yelp  0.500306  0.098362  0.094000

### 3. Model_3

In [10]:
model_3_aucroc_scores = []
model_3_aucpr_scores = []
model_3_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_3_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_3_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_3_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_3_f1_scores.append(f1)

# compute average scores of all datasets
model_3_avg_aucroc = sum(model_3_aucroc_scores) / len(model_3_aucroc_scores)
model_3_avg_aucpr = sum(model_3_aucpr_scores) / len(model_3_aucpr_scores)
model_3_avg_f1 = sum(model_3_f1_scores) / len(model_3_f1_scores)

print(f"number of datasets: {len(model_3_aucroc_scores)}")
print(f"Average aucroc: {model_3_avg_aucroc}")
print(f"Average aucpr: {model_3_avg_aucpr}")
print(f"Average f1: {model_3_avg_f1}")

number of datasets: 121
Average aucroc: 0.7249775360785166
Average aucpr: 0.4341971090507112
Average f1: 0.41580002920536835

In [11]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_3_dict = {'dataset': datasets_name, 'aucroc': model_3_aucroc_scores, 'aucpr': model_3_aucpr_scores, 'f1': model_3_f1_scores}
model_3_df = pd.DataFrame(model_3_dict)
model_3_top10_worst_aucroc = model_3_df.sort_values(by='aucroc', ascending=True).head(10)
model_3_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
13           9_census  0.356846  0.086842  0.049661
113         20_letter  0.419547  0.093431  0.010000
83          36_speech  0.427441  0.028982  0.000000
53               imdb  0.453884  0.083396  0.062000
23           20news_1  0.475756  0.086940  0.064000
46   MNIST-C_identity  0.481370  0.090175  0.090000
107            SVHN_8  0.490255  0.105410  0.113208
120            SVHN_0  0.494893  0.094493  0.065385
115            SVHN_6  0.495449  0.111673  0.112957
10           12_fault  0.501064  0.580045  0.521545

### 4. Model_4

In [12]:
model_4_aucroc_scores = []
model_4_aucpr_scores = []
model_4_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_4_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_4_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_4_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_4_f1_scores.append(f1)

# compute average scores of all datasets
model_4_avg_aucroc = sum(model_4_aucroc_scores) / len(model_4_aucroc_scores)
model_4_avg_aucpr = sum(model_4_aucpr_scores) / len(model_4_aucpr_scores)
model_4_avg_f1 = sum(model_4_f1_scores) / len(model_4_f1_scores)

print(f"number of datasets: {len(model_4_aucroc_scores)}")
print(f"Average aucroc: {model_4_avg_aucroc}")
print(f"Average aucpr: {model_4_avg_aucpr}")
print(f"Average f1: {model_4_avg_f1}")

number of datasets: 121
Average aucroc: 0.721563656216457
Average aucpr: 0.42834347411031626
Average f1: 0.41139869785448663

In [13]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_4_dict = {'dataset': datasets_name, 'aucroc': model_4_aucroc_scores, 'aucpr': model_4_aucpr_scores, 'f1': model_4_f1_scores}
model_4_df = pd.DataFrame(model_4_dict)
model_4_top10_worst_aucroc = model_4_df.sort_values(by='aucroc', ascending=True).head(10)
model_4_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
16            33_skin  0.145821  0.212688  0.086205
113         20_letter  0.414347  0.094273  0.050000
83          36_speech  0.431953  0.030243  0.016393
111          8_celeba  0.433690  0.033806  0.016023
53               imdb  0.440821  0.083082  0.060000
67         3_backdoor  0.477762  0.079239  0.103420
46   MNIST-C_identity  0.490594  0.092800  0.084000
57           20news_2  0.491674  0.097910  0.088710
86           20news_4  0.494437  0.103774  0.097561
88               yelp  0.498113  0.099995  0.110000

### 5. model_5

In [14]:
model_5_aucroc_scores = []
model_5_aucpr_scores = []
model_5_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_5_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_5_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_5_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_5_f1_scores.append(f1)

# compute average scores of all datasets
model_5_avg_aucroc = sum(model_5_aucroc_scores) / len(model_5_aucroc_scores)
model_5_avg_aucpr = sum(model_5_aucpr_scores) / len(model_5_aucpr_scores)
model_5_avg_f1 = sum(model_5_f1_scores) / len(model_5_f1_scores)

print(f"number of datasets: {len(model_5_aucroc_scores)}")
print(f"Average aucroc: {model_5_avg_aucroc}")
print(f"Average aucpr: {model_5_avg_aucpr}")
print(f"Average f1: {model_5_avg_f1}")

number of datasets: 121
Average aucroc: 0.7219098312030479
Average aucpr: 0.42651203259347353
Average f1: 0.4145596581983032

In [15]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_5_dict = {'dataset': datasets_name, 'aucroc': model_5_aucroc_scores, 'aucpr': model_5_aucpr_scores, 'f1': model_5_f1_scores}
model_5_df = pd.DataFrame(model_5_dict)
model_5_top10_worst_aucroc = model_5_df.sort_values(by='aucroc', ascending=True).head(10)
model_5_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
111          8_celeba  0.406005  0.032615  0.011310
113         20_letter  0.422313  0.125797  0.060000
83          36_speech  0.440887  0.028857  0.016393
16            33_skin  0.456028  0.309118  0.154841
58           20news_5  0.460535  0.100257  0.105263
35         19_landsat  0.466548  0.391968  0.309077
23           20news_1  0.472033  0.086806  0.080000
118         CIFAR10_5  0.475948  0.091556  0.076046
53               imdb  0.479037  0.094855  0.094000
46   MNIST-C_identity  0.501841  0.095219  0.084000

### 6. model_6

In [16]:
model_6_aucroc_scores = []
model_6_aucpr_scores = []
model_6_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_6_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_6_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_6_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_6_f1_scores.append(f1)

# compute average scores of all datasets
model_6_avg_aucroc = sum(model_6_aucroc_scores) / len(model_6_aucroc_scores)
model_6_avg_aucpr = sum(model_6_aucpr_scores) / len(model_6_aucpr_scores)
model_6_avg_f1 = sum(model_6_f1_scores) / len(model_6_f1_scores)

print(f"number of datasets: {len(model_6_aucroc_scores)}")
print(f"Average aucroc: {model_6_avg_aucroc}")
print(f"Average aucpr: {model_6_avg_aucpr}")
print(f"Average f1: {model_6_avg_f1}")

number of datasets: 121
Average aucroc: 0.7302896791195459
Average aucpr: 0.4375916966726926
Average f1: 0.42914383875052026

In [17]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_6_dict = {'dataset': datasets_name, 'aucroc': model_6_aucroc_scores, 'aucpr': model_6_aucpr_scores, 'f1': model_6_f1_scores}
model_6_df = pd.DataFrame(model_6_dict)
model_6_top10_worst_aucroc = model_6_df.sort_values(by='aucroc', ascending=True).head(10)
model_6_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
67         3_backdoor  0.394192  0.064638  0.114821
83          36_speech  0.424783  0.029288  0.000000
113         20_letter  0.427153  0.097407  0.050000
16            33_skin  0.448617  0.290907  0.277150
53               imdb  0.451367  0.083487  0.062000
26          CIFAR10_3  0.462541  0.090770  0.095057
23           20news_1  0.472100  0.090959  0.088000
118         CIFAR10_5  0.475837  0.088271  0.072243
13           9_census  0.483251  0.123391  0.152209
46   MNIST-C_identity  0.488804  0.092370  0.090000

### 7. model_7

In [18]:
model_7_aucroc_scores = []
model_7_aucpr_scores = []
model_7_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_7_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_7_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_7_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_7_f1_scores.append(f1)

# compute average scores of all datasets
model_7_avg_aucroc = sum(model_7_aucroc_scores) / len(model_7_aucroc_scores)
model_7_avg_aucpr = sum(model_7_aucpr_scores) / len(model_7_aucpr_scores)
model_7_avg_f1 = sum(model_7_f1_scores) / len(model_7_f1_scores)

print(f"number of datasets: {len(model_7_aucroc_scores)}")
print(f"Average aucroc: {model_7_avg_aucroc}")
print(f"Average aucpr: {model_7_avg_aucpr}")
print(f"Average f1: {model_7_avg_f1}")

number of datasets: 121
Average aucroc: 0.7449773495919908
Average aucpr: 0.4452134649671709
Average f1: 0.4320967724162309

In [19]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_7_dict = {'dataset': datasets_name, 'aucroc': model_7_aucroc_scores, 'aucpr': model_7_aucpr_scores, 'f1': model_7_f1_scores}
model_7_df = pd.DataFrame(model_7_dict)
model_7_top10_worst_aucroc = model_7_df.sort_values(by='aucroc', ascending=True).head(10)
model_7_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
16            33_skin  0.200750  0.219345  0.120089
113         20_letter  0.408253  0.111337  0.060000
83          36_speech  0.423955  0.028246  0.000000
120            SVHN_0  0.459294  0.096887  0.069231
57           20news_2  0.468156  0.092607  0.096774
53               imdb  0.473440  0.088544  0.068000
35         19_landsat  0.482228  0.378403  0.258065
59           47_yeast  0.483444  0.503901  0.499014
103    MNIST-C_rotate  0.484414  0.097688  0.116000
46   MNIST-C_identity  0.501908  0.094427  0.082000

### 8. model_8

In [20]:
model_8_aucroc_scores = []
model_8_aucpr_scores = []
model_8_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_8_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_8_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_8_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_8_f1_scores.append(f1)

# compute average scores of all datasets
model_8_avg_aucroc = sum(model_8_aucroc_scores) / len(model_8_aucroc_scores)
model_8_avg_aucpr = sum(model_8_aucpr_scores) / len(model_8_aucpr_scores)
model_8_avg_f1 = sum(model_8_f1_scores) / len(model_8_f1_scores)

print(f"number of datasets: {len(model_8_aucroc_scores)}")
print(f"Average aucroc: {model_8_avg_aucroc}")
print(f"Average aucpr: {model_8_avg_aucpr}")
print(f"Average f1: {model_8_avg_f1}")

number of datasets: 121
Average aucroc: 0.7242999626159644
Average aucpr: 0.4379644598096458
Average f1: 0.4264069968411738

In [21]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_8_dict = {'dataset': datasets_name, 'aucroc': model_8_aucroc_scores, 'aucpr': model_8_aucpr_scores, 'f1': model_8_f1_scores}
model_8_df = pd.DataFrame(model_8_dict)
model_8_top10_worst_aucroc = model_8_df.sort_values(by='aucroc', ascending=True).head(10)
model_8_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
83          36_speech  0.378008  0.025400  0.000000
113         20_letter  0.429047  0.097372  0.050000
19     17_InternetAds  0.435793  0.316868  0.266304
35         19_landsat  0.458877  0.381091  0.336084
53               imdb  0.468941  0.087052  0.062000
59           47_yeast  0.478677  0.506616  0.493097
46   MNIST-C_identity  0.492168  0.095973  0.104000
118         CIFAR10_5  0.504920  0.098315  0.087452
50         5_campaign  0.511505  0.207095  0.159914
57           20news_2  0.514638  0.103272  0.137097

### 3. model_9

In [22]:
model_9_aucroc_scores = []
model_9_aucpr_scores = []
model_9_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_9_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_9_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_9_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_9_f1_scores.append(f1)

# compute average scores of all datasets
model_9_avg_aucroc = sum(model_9_aucroc_scores) / len(model_9_aucroc_scores)
model_9_avg_aucpr = sum(model_9_aucpr_scores) / len(model_9_aucpr_scores)
model_9_avg_f1 = sum(model_9_f1_scores) / len(model_9_f1_scores)

print(f"number of datasets: {len(model_9_aucroc_scores)}")
print(f"Average aucroc: {model_9_avg_aucroc}")
print(f"Average aucpr: {model_9_avg_aucpr}")
print(f"Average f1: {model_9_avg_f1}")

number of datasets: 121
Average aucroc: 0.7521430308523781
Average aucpr: 0.45772192099877795
Average f1: 0.44376954039264516

In [23]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_9_dict = {'dataset': datasets_name, 'aucroc': model_9_aucroc_scores, 'aucpr': model_9_aucpr_scores, 'f1': model_9_f1_scores}
model_9_df = pd.DataFrame(model_9_dict)
model_9_top10_worst_aucroc = model_9_df.sort_values(by='aucroc', ascending=True).head(10)
model_9_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
83          36_speech  0.403181  0.026907  0.000000
113         20_letter  0.419053  0.125195  0.060000
53               imdb  0.432631  0.080803  0.056000
57           20news_2  0.476071  0.092324  0.088710
35         19_landsat  0.486679  0.423293  0.368342
59           47_yeast  0.487591  0.507762  0.502959
46   MNIST-C_identity  0.489682  0.090933  0.082000
103    MNIST-C_rotate  0.511574  0.098390  0.090000
86           20news_4  0.512861  0.109892  0.134146
118         CIFAR10_5  0.524592  0.103525  0.098859

### 10. model_10

In [24]:
model_10_aucroc_scores = []
model_10_aucpr_scores = []
model_10_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_10_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_10_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_10_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_10_f1_scores.append(f1)

# compute average scores of all datasets
model_10_avg_aucroc = sum(model_10_aucroc_scores) / len(model_10_aucroc_scores)
model_10_avg_aucpr = sum(model_10_aucpr_scores) / len(model_10_aucpr_scores)
model_10_avg_f1 = sum(model_10_f1_scores) / len(model_10_f1_scores)

print(f"number of datasets: {len(model_10_aucroc_scores)}")
print(f"Average aucroc: {model_10_avg_aucroc}")
print(f"Average aucpr: {model_10_avg_aucpr}")
print(f"Average f1: {model_10_avg_f1}")

number of datasets: 121
Average aucroc: 0.7136679883518433
Average aucpr: 0.4131092076130957
Average f1: 0.4029863578726533

In [25]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_10_dict = {'dataset': datasets_name, 'aucroc': model_10_aucroc_scores, 'aucpr': model_10_aucpr_scores, 'f1': model_10_f1_scores}
model_10_df = pd.DataFrame(model_10_dict)
model_10_top10_worst_aucroc = model_10_df.sort_values(by='aucroc', ascending=True).head(10)
model_10_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
16            33_skin  0.339461  0.263481  0.164109
83          36_speech  0.401852  0.026348  0.000000
113         20_letter  0.431940  0.099492  0.080000
53               imdb  0.466939  0.089334  0.072000
62           agnews_3  0.473195  0.093100  0.096000
59           47_yeast  0.473631  0.498379  0.497041
35         19_landsat  0.479054  0.386625  0.300825
23           20news_1  0.483930  0.088579  0.056000
92             amazon  0.485857  0.095589  0.106000
46   MNIST-C_identity  0.495123  0.095035  0.098000

### 11. model_11

In [26]:
model_11_aucroc_scores = []
model_11_aucpr_scores = []
model_11_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_11_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_11_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_11_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_11_f1_scores.append(f1)

# compute average scores of all datasets
model_11_avg_aucroc = sum(model_11_aucroc_scores) / len(model_11_aucroc_scores)
model_11_avg_aucpr = sum(model_11_aucpr_scores) / len(model_11_aucpr_scores)
model_11_avg_f1 = sum(model_11_f1_scores) / len(model_11_f1_scores)

print(f"number of datasets: {len(model_11_aucroc_scores)}")
print(f"Average aucroc: {model_11_avg_aucroc}")
print(f"Average aucpr: {model_11_avg_aucpr}")
print(f"Average f1: {model_11_avg_f1}")

number of datasets: 121
Average aucroc: 0.725556983095233
Average aucpr: 0.43704232614601246
Average f1: 0.42408096711495363

In [27]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_11_dict = {'dataset': datasets_name, 'aucroc': model_11_aucroc_scores, 'aucpr': model_11_aucpr_scores, 'f1': model_11_f1_scores}
model_11_df = pd.DataFrame(model_11_dict)
model_11_top10_worst_aucroc = model_11_df.sort_values(by='aucroc', ascending=True).head(10)
model_11_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
83          36_speech  0.372619  0.025097  0.000000
113         20_letter  0.395720  0.100752  0.050000
53               imdb  0.477955  0.088174  0.062000
59           47_yeast  0.482952  0.505833  0.500986
50         5_campaign  0.486802  0.201365  0.171983
118         CIFAR10_5  0.490146  0.096696  0.087452
46   MNIST-C_identity  0.490314  0.097401  0.112000
117            SVHN_9  0.496456  0.107676  0.118367
120            SVHN_0  0.503440  0.102382  0.119231
26          CIFAR10_3  0.505092  0.111847  0.125475

### 12. model_12

In [28]:
model_12_aucroc_scores = []
model_12_aucpr_scores = []
model_12_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_12_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_12_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_12_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_12_f1_scores.append(f1)

# compute average scores of all datasets
model_12_avg_aucroc = sum(model_12_aucroc_scores) / len(model_12_aucroc_scores)
model_12_avg_aucpr = sum(model_12_aucpr_scores) / len(model_12_aucpr_scores)
model_12_avg_f1 = sum(model_12_f1_scores) / len(model_12_f1_scores)

print(f"number of datasets: {len(model_12_aucroc_scores)}")
print(f"Average aucroc: {model_12_avg_aucroc}")
print(f"Average aucpr: {model_12_avg_aucpr}")
print(f"Average f1: {model_12_avg_f1}")

number of datasets: 121
Average aucroc: 0.7229310793672145
Average aucpr: 0.43560477956189186
Average f1: 0.41955493190108356

In [29]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_12_dict = {'dataset': datasets_name, 'aucroc': model_12_aucroc_scores, 'aucpr': model_12_aucpr_scores, 'f1': model_12_f1_scores}
model_12_df = pd.DataFrame(model_12_dict)
model_12_top10_worst_aucroc = model_12_df.sort_values(by='aucroc', ascending=True).head(10)
model_12_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
19     17_InternetAds  0.276705  0.392105  0.225543
83          36_speech  0.423824  0.027525  0.016393
67         3_backdoor  0.432821  0.091135  0.107492
59           47_yeast  0.442141  0.491142  0.455621
113         20_letter  0.461453  0.099899  0.040000
17             SVHN_1  0.472944  0.086835  0.074000
103    MNIST-C_rotate  0.479558  0.094424  0.108000
35         19_landsat  0.488665  0.381206  0.288822
46   MNIST-C_identity  0.500177  0.094282  0.098000
115            SVHN_6  0.501720  0.110013  0.102990

### 13. model_13

In [30]:
model_13_aucroc_scores = []
model_13_aucpr_scores = []
model_13_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_13_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_13_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_13_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_13_f1_scores.append(f1)

# compute average scores of all datasets
model_13_avg_aucroc = sum(model_13_aucroc_scores) / len(model_13_aucroc_scores)
model_13_avg_aucpr = sum(model_13_aucpr_scores) / len(model_13_aucpr_scores)
model_13_avg_f1 = sum(model_13_f1_scores) / len(model_13_f1_scores)

print(f"number of datasets: {len(model_13_aucroc_scores)}")
print(f"Average aucroc: {model_13_avg_aucroc}")
print(f"Average aucpr: {model_13_avg_aucpr}")
print(f"Average f1: {model_13_avg_f1}")

number of datasets: 121
Average aucroc: 0.7089892118566757
Average aucpr: 0.43801403112206405
Average f1: 0.424991055002042

In [31]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_13_dict = {'dataset': datasets_name, 'aucroc': model_13_aucroc_scores, 'aucpr': model_13_aucpr_scores, 'f1': model_13_f1_scores}
model_13_df = pd.DataFrame(model_13_dict)
model_13_top10_worst_aucroc = model_13_df.sort_values(by='aucroc', ascending=True).head(10)
model_13_top10_worst_aucroc

                dataset    aucroc     aucpr        f1
19       17_InternetAds  0.126864  0.311389  0.057065
67           3_backdoor  0.242723  0.089607  0.095277
13             9_census  0.274897  0.156059  0.194453
83            36_speech  0.379391  0.025525  0.000000
113           20_letter  0.424707  0.096191  0.040000
118           CIFAR10_5  0.451916  0.090256  0.087452
59             47_yeast  0.462398  0.492879  0.479290
74      MNIST-C_spatter  0.466419  0.106860  0.106000
99   MNIST-C_brightness  0.467391  0.104273  0.110000
53                 imdb  0.482407  0.090108  0.072000

In [32]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_13_dict = {'dataset': datasets_name, 'aucroc': model_13_aucroc_scores, 'aucpr': model_13_aucpr_scores, 'f1': model_13_f1_scores}
model_13_df = pd.DataFrame(model_13_dict)
model_13_top10_best_aucroc = model_13_df.sort_values(by='aucroc', ascending=False).head(10)
model_13_top10_best_aucroc

             dataset    aucroc     aucpr        f1
38      15_Hepatitis  1.000000  1.000000  1.000000
119          45_wine  1.000000  1.000000  1.000000
89   21_Lymphography  1.000000  1.000000  1.000000
47           43_WDBC  1.000000  1.000000  1.000000
114        11_donors  0.999947  0.999555  0.991747
96           16_http  0.999921  0.980901  0.989796
76        32_shuttle  0.999148  0.993673  0.982341
36           25_musk  0.998867  0.977970  0.938144
98          10_cover  0.995407  0.861382  0.816810
7             42_WBC  0.993711  0.938527  0.847826

### 14. model_14

In [33]:
model_14_aucroc_scores = []
model_14_aucpr_scores = []
model_14_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_14_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_14_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_14_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_14_f1_scores.append(f1)

# compute average scores of all datasets
model_14_avg_aucroc = sum(model_14_aucroc_scores) / len(model_14_aucroc_scores)
model_14_avg_aucpr = sum(model_14_aucpr_scores) / len(model_14_aucpr_scores)
model_14_avg_f1 = sum(model_14_f1_scores) / len(model_14_f1_scores)

print(f"number of datasets: {len(model_14_aucroc_scores)}")
print(f"Average aucroc: {model_14_avg_aucroc}")
print(f"Average aucpr: {model_14_avg_aucpr}")
print(f"Average f1: {model_14_avg_f1}")

number of datasets: 121
Average aucroc: 0.7412423021517344
Average aucpr: 0.45290260747567684
Average f1: 0.44255015519802304

In [34]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_14_dict = {'dataset': datasets_name, 'aucroc': model_14_aucroc_scores, 'aucpr': model_14_aucpr_scores, 'f1': model_14_f1_scores}
model_14_df = pd.DataFrame(model_14_dict)
model_14_top10_worst_aucroc = model_14_df.sort_values(by='aucroc', ascending=True).head(10)
model_14_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
111          8_celeba  0.292302  0.026660  0.000943
113         20_letter  0.405173  0.106062  0.050000
83          36_speech  0.405225  0.026249  0.000000
16            33_skin  0.422467  0.360994  0.284487
57           20news_2  0.469780  0.092321  0.088710
59           47_yeast  0.472679  0.499794  0.473373
53               imdb  0.479198  0.088142  0.070000
120            SVHN_0  0.487625  0.097692  0.084615
103    MNIST-C_rotate  0.492946  0.095105  0.102000
46   MNIST-C_identity  0.504136  0.094248  0.088000

### 15. model_15

In [35]:
model_15_aucroc_scores = []
model_15_aucpr_scores = []
model_15_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_15_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_15_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_15_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_15_f1_scores.append(f1)

# compute average scores of all datasets
model_15_avg_aucroc = sum(model_15_aucroc_scores) / len(model_15_aucroc_scores)
model_15_avg_aucpr = sum(model_15_aucpr_scores) / len(model_15_aucpr_scores)
model_15_avg_f1 = sum(model_15_f1_scores) / len(model_15_f1_scores)

print(f"number of datasets: {len(model_15_aucroc_scores)}")
print(f"Average aucroc: {model_15_avg_aucroc}")
print(f"Average aucpr: {model_15_avg_aucpr}")
print(f"Average f1: {model_15_avg_f1}")

number of datasets: 121
Average aucroc: 0.7305661297843214
Average aucpr: 0.4332131687995652
Average f1: 0.41815362385150306

In [36]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_15_dict = {'dataset': datasets_name, 'aucroc': model_15_aucroc_scores, 'aucpr': model_15_aucpr_scores, 'f1': model_15_f1_scores}
model_15_df = pd.DataFrame(model_15_dict)
model_15_top10_worst_aucroc = model_15_df.sort_values(by='aucroc', ascending=True).head(10)
model_15_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
19     17_InternetAds  0.403094  0.385339  0.432065
53               imdb  0.421172  0.077843  0.046000
113         20_letter  0.423040  0.117968  0.040000
16            33_skin  0.428408  0.363776  0.267690
23           20news_1  0.461811  0.089102  0.096000
83          36_speech  0.470174  0.030719  0.000000
57           20news_2  0.477926  0.091757  0.096774
46   MNIST-C_identity  0.483659  0.090605  0.082000
59           47_yeast  0.487893  0.522668  0.493097
120            SVHN_0  0.490235  0.100814  0.088462

### 16. model_16

In [37]:
model_16_aucroc_scores = []
model_16_aucpr_scores = []
model_16_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_16_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_16_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_16_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_16_f1_scores.append(f1)

# compute average scores of all datasets
model_16_avg_aucroc = sum(model_16_aucroc_scores) / len(model_16_aucroc_scores)
model_16_avg_aucpr = sum(model_16_aucpr_scores) / len(model_16_aucpr_scores)
model_16_avg_f1 = sum(model_16_f1_scores) / len(model_16_f1_scores)

print(f"number of datasets: {len(model_16_aucroc_scores)}")
print(f"Average aucroc: {model_16_avg_aucroc}")
print(f"Average aucpr: {model_16_avg_aucpr}")
print(f"Average f1: {model_16_avg_f1}")

number of datasets: 121
Average aucroc: 0.718831008238944
Average aucpr: 0.4143078253265656
Average f1: 0.4105904828558075

In [38]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_16_dict = {'dataset': datasets_name, 'aucroc': model_16_aucroc_scores, 'aucpr': model_16_aucpr_scores, 'f1': model_16_f1_scores}
model_16_df = pd.DataFrame(model_16_dict)
model_16_top10_worst_aucroc = model_16_df.sort_values(by='aucroc', ascending=True).head(10)
model_16_top10_worst_aucroc

                   dataset    aucroc     aucpr        f1
19          17_InternetAds  0.409187  0.419047  0.432065
113              20_letter  0.415267  0.113640  0.060000
11               CIFAR10_9  0.428739  0.079310  0.060837
115                 SVHN_6  0.454958  0.103892  0.112957
67              3_backdoor  0.461054  0.177903  0.144951
64      MNIST-C_shot_noise  0.467830  0.124497  0.210000
20   MNIST-C_impulse_noise  0.473518  0.156824  0.182000
13                9_census  0.473556  0.121626  0.159948
83               36_speech  0.486161  0.034616  0.016393
23                20news_1  0.489459  0.095307  0.080000

### 17. model_17

In [39]:
model_17_aucroc_scores = []
model_17_aucpr_scores = []
model_17_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_17_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_17_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_17_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_17_f1_scores.append(f1)

# compute average scores of all datasets
model_17_avg_aucroc = sum(model_17_aucroc_scores) / len(model_17_aucroc_scores)
model_17_avg_aucpr = sum(model_17_aucpr_scores) / len(model_17_aucpr_scores)
model_17_avg_f1 = sum(model_17_f1_scores) / len(model_17_f1_scores)

print(f"number of datasets: {len(model_17_aucroc_scores)}")
print(f"Average aucroc: {model_17_avg_aucroc}")
print(f"Average aucpr: {model_17_avg_aucpr}")
print(f"Average f1: {model_17_avg_f1}")

number of datasets: 121
Average aucroc: 0.7543135602336452
Average aucpr: 0.46283737924489415
Average f1: 0.44964600208984595

In [40]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_17_dict = {'dataset': datasets_name, 'aucroc': model_17_aucroc_scores, 'aucpr': model_17_aucpr_scores, 'f1': model_17_f1_scores}
model_17_df = pd.DataFrame(model_17_dict)
model_17_top10_worst_aucroc = model_17_df.sort_values(by='aucroc', ascending=True).head(10)
model_17_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
111          8_celeba  0.408335  0.031744  0.000000
83          36_speech  0.427387  0.027511  0.000000
113         20_letter  0.429240  0.104054  0.060000
59           47_yeast  0.448123  0.489690  0.463511
57           20news_2  0.484944  0.092241  0.088710
53               imdb  0.488067  0.090480  0.072000
46   MNIST-C_identity  0.488702  0.091230  0.090000
51          CIFAR10_1  0.496967  0.093726  0.083650
23           20news_1  0.509322  0.096127  0.080000
120            SVHN_0  0.530486  0.111972  0.150000

### 18. model_18 (SquareGMM of Simon)

In [41]:
model_18_aucroc_scores = []
model_18_aucpr_scores = []
model_18_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_18_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_18_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_18_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_18_f1_scores.append(f1)

# compute average scores of all datasets
model_18_avg_aucroc = sum(model_18_aucroc_scores) / len(model_18_aucroc_scores)
model_18_avg_aucpr = sum(model_18_aucpr_scores) / len(model_18_aucpr_scores)
model_18_avg_f1 = sum(model_18_f1_scores) / len(model_18_f1_scores)

print(f"number of datasets: {len(model_18_aucroc_scores)}")
print(f"Average aucroc: {model_18_avg_aucroc}")
print(f"Average aucpr: {model_18_avg_aucpr}")
print(f"Average f1: {model_18_avg_f1}")

number of datasets: 121
Average aucroc: 0.7664115769172253
Average aucpr: 0.44113147204850495
Average f1: 0.4421199694683027

In [42]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_18_dict = {'dataset': datasets_name, 'aucroc': model_18_aucroc_scores, 'aucpr': model_18_aucpr_scores, 'f1': model_18_f1_scores}
model_18_df = pd.DataFrame(model_18_dict)
model_18_top10_worst_aucroc = model_18_df.sort_values(by='aucroc', ascending=True).head(10)
model_18_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
83          36_speech  0.453627  0.031839  0.032787
46   MNIST-C_identity  0.466429  0.087364  0.080000
59           47_yeast  0.466955  0.496813  0.467456
118         CIFAR10_5  0.469436  0.089497  0.068441
53               imdb  0.469793  0.086711  0.062000
57           20news_2  0.481126  0.094466  0.080645
26          CIFAR10_3  0.488716  0.097428  0.121673
117            SVHN_9  0.491764  0.100962  0.106122
23           20news_1  0.496991  0.097254  0.064000
107            SVHN_8  0.515880  0.125178  0.139623

### 19. model_19

In [43]:
model_19_aucroc_scores = []
model_19_aucpr_scores = []
model_19_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_19_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_19_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_19_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_19_f1_scores.append(f1)

# compute average scores of all datasets
model_19_avg_aucroc = sum(model_19_aucroc_scores) / len(model_19_aucroc_scores)
model_19_avg_aucpr = sum(model_19_aucpr_scores) / len(model_19_aucpr_scores)
model_19_avg_f1 = sum(model_19_f1_scores) / len(model_19_f1_scores)

print(f"number of datasets: {len(model_19_aucroc_scores)}")
print(f"Average aucroc: {model_19_avg_aucroc}")
print(f"Average aucpr: {model_19_avg_aucpr}")
print(f"Average f1: {model_19_avg_f1}")

number of datasets: 121
Average aucroc: 0.7632214324103633
Average aucpr: 0.44742753311961825
Average f1: 0.44871271231331616

In [44]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_19_dict = {'dataset': datasets_name, 'aucroc': model_19_aucroc_scores, 'aucpr': model_19_aucpr_scores, 'f1': model_19_f1_scores}
model_19_df = pd.DataFrame(model_19_dict)
model_19_top10_worst_aucroc = model_19_df.sort_values(by='aucroc', ascending=True).head(10)
model_19_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
19     17_InternetAds  0.431895  0.397294  0.301630
59           47_yeast  0.444699  0.487998  0.465483
53               imdb  0.454090  0.082690  0.060000
83          36_speech  0.456476  0.029061  0.000000
46   MNIST-C_identity  0.483323  0.088703  0.078000
118         CIFAR10_5  0.484433  0.089093  0.076046
26          CIFAR10_3  0.503501  0.098618  0.098859
10           12_fault  0.514712  0.545658  0.518574
92             amazon  0.516366  0.099092  0.104000
35         19_landsat  0.520746  0.460195  0.416354

### 20. model_20 (originally test with Epochs=100, but it's broken after 50 epochs)

In [45]:
model_20_aucroc_scores = []
model_20_aucpr_scores = []
model_20_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_20_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_20_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_20_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_20_f1_scores.append(f1)

# compute average scores of all datasets
model_20_avg_aucroc = sum(model_20_aucroc_scores) / len(model_20_aucroc_scores)
model_20_avg_aucpr = sum(model_20_aucpr_scores) / len(model_20_aucpr_scores)
model_20_avg_f1 = sum(model_20_f1_scores) / len(model_20_f1_scores)

print(f"number of datasets: {len(model_20_aucroc_scores)}")
print(f"Average aucroc: {model_20_avg_aucroc}")
print(f"Average aucpr: {model_20_avg_aucpr}")
print(f"Average f1: {model_20_avg_f1}")

number of datasets: 121
Average aucroc: 0.7394919288952985
Average aucpr: 0.44996199190833225
Average f1: 0.4323942546639789

In [46]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_20_dict = {'dataset': datasets_name, 'aucroc': model_20_aucroc_scores, 'aucpr': model_20_aucpr_scores, 'f1': model_20_f1_scores}
model_20_df = pd.DataFrame(model_20_dict)
model_20_top10_worst_aucroc = model_20_df.sort_values(by='aucroc', ascending=True).head(10)
model_20_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
83          36_speech  0.405812  0.025658  0.000000
113         20_letter  0.425040  0.122411  0.060000
59           47_yeast  0.455706  0.496890  0.475345
92             amazon  0.474709  0.088513  0.070000
102          20news_3  0.483718  0.103262  0.066667
53               imdb  0.493333  0.092615  0.090000
57           20news_2  0.495740  0.096488  0.104839
46   MNIST-C_identity  0.496103  0.093499  0.094000
23           20news_1  0.501469  0.093712  0.080000
80          CIFAR10_2  0.502041  0.108848  0.148289

In [47]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_20_dict = {'dataset': datasets_name, 'aucroc': model_20_aucroc_scores, 'aucpr': model_20_aucpr_scores, 'f1': model_20_f1_scores}
model_20_df = pd.DataFrame(model_20_dict)
model_20_top10_best_aucroc = model_20_df.sort_values(by='aucroc', ascending=False).head(10)
model_20_top10_best_aucroc

                   dataset    aucroc     aucpr        f1
89         21_Lymphography  1.000000  1.000000  1.000000
119                45_wine  1.000000  1.000000  1.000000
38            15_Hepatitis  1.000000  1.000000  1.000000
20   MNIST-C_impulse_noise  0.999973  0.999749  0.990000
47                 43_WDBC  0.999644  0.993043  0.913043
96                 16_http  0.999305  0.905560  0.908163
114              11_donors  0.999302  0.983584  0.980055
76              32_shuttle  0.998908  0.992418  0.980063
7                   42_WBC  0.997539  0.967732  0.956522
5           MNIST-C_stripe  0.996235  0.974003  0.920000

### 21. model_21

In [48]:
model_21_aucroc_scores = []
model_21_aucpr_scores = []
model_21_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_21_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_21_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_21_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_21_f1_scores.append(f1)

# compute average scores of all datasets
model_21_avg_aucroc = sum(model_21_aucroc_scores) / len(model_21_aucroc_scores)
model_21_avg_aucpr = sum(model_21_aucpr_scores) / len(model_21_aucpr_scores)
model_21_avg_f1 = sum(model_21_f1_scores) / len(model_21_f1_scores)

print(f"number of datasets: {len(model_21_aucroc_scores)}")
print(f"Average aucroc: {model_21_avg_aucroc}")
print(f"Average aucpr: {model_21_avg_aucpr}")
print(f"Average f1: {model_21_avg_f1}")

number of datasets: 121
Average aucroc: 0.7542847496711391
Average aucpr: 0.4382576708881854
Average f1: 0.43434708299171737

In [49]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_21_dict = {'dataset': datasets_name, 'aucroc': model_21_aucroc_scores, 'aucpr': model_21_aucpr_scores, 'f1': model_21_f1_scores}
model_21_df = pd.DataFrame(model_21_dict)
model_21_top10_worst_aucroc = model_21_df.sort_values(by='aucroc', ascending=True).head(10)
model_21_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
96            16_http  0.382932  0.027130  0.040816
59           47_yeast  0.455916  0.485503  0.471400
19     17_InternetAds  0.466908  0.410393  0.328804
83          36_speech  0.469560  0.031748  0.016393
46   MNIST-C_identity  0.478170  0.088179  0.068000
53               imdb  0.481302  0.087970  0.076000
118         CIFAR10_5  0.483127  0.093126  0.098859
26          CIFAR10_3  0.491109  0.094062  0.106464
51          CIFAR10_1  0.491197  0.088143  0.057034
57           20news_2  0.509892  0.103134  0.088710

In [50]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_21_dict = {'dataset': datasets_name, 'aucroc': model_21_aucroc_scores, 'aucpr': model_21_aucpr_scores, 'f1': model_21_f1_scores}
model_21_df = pd.DataFrame(model_21_dict)
model_21_top10_best_aucroc = model_21_df.sort_values(by='aucroc', ascending=False).head(10)
model_21_top10_best_aucroc

                   dataset    aucroc     aucpr        f1
119                45_wine  1.000000  1.000000  1.000000
89         21_Lymphography  1.000000  1.000000  1.000000
38            15_Hepatitis  1.000000  1.000000  1.000000
20   MNIST-C_impulse_noise  0.999129  0.988885  0.960000
5           MNIST-C_stripe  0.996434  0.970699  0.912000
47                 43_WDBC  0.995732  0.940613  0.826087
7                   42_WBC  0.995306  0.928735  0.891304
98                10_cover  0.993689  0.705658  0.745690
114              11_donors  0.992874  0.850290  0.930880
76              32_shuttle  0.991081  0.917043  0.948448

### 22. model_22

In [51]:
model_22_aucroc_scores = []
model_22_aucpr_scores = []
model_22_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_22_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_22_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_22_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_22_f1_scores.append(f1)

# compute average scores of all datasets
model_22_avg_aucroc = sum(model_22_aucroc_scores) / len(model_22_aucroc_scores)
model_22_avg_aucpr = sum(model_22_aucpr_scores) / len(model_22_aucpr_scores)
model_22_avg_f1 = sum(model_22_f1_scores) / len(model_22_f1_scores)

print(f"number of datasets: {len(model_22_aucroc_scores)}")
print(f"Average aucroc: {model_22_avg_aucroc}")
print(f"Average aucpr: {model_22_avg_aucpr}")
print(f"Average f1: {model_22_avg_f1}")

number of datasets: 121
Average aucroc: 0.7692643131977385
Average aucpr: 0.44905888404148675
Average f1: 0.4493582619772472

In [53]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_22_dict = {'dataset': datasets_name, 'aucroc': model_22_aucroc_scores, 'aucpr': model_22_aucpr_scores, 'f1': model_22_f1_scores}
model_22_df = pd.DataFrame(model_22_dict)
model_22_top10_worst_aucroc = model_22_df.sort_values(by='aucroc', ascending=True).head(10)
model_22_top10_worst_aucroc

              dataset    aucroc     aucpr        f1
83          36_speech  0.446846  0.028859  0.016393
59           47_yeast  0.452128  0.488570  0.471400
53               imdb  0.454000  0.083052  0.058000
19     17_InternetAds  0.460450  0.407603  0.342391
36            25_musk  0.472878  0.053112  0.000000
118         CIFAR10_5  0.483110  0.090662  0.068441
46   MNIST-C_identity  0.487759  0.089353  0.072000
23           20news_1  0.492003  0.098816  0.120000
92             amazon  0.501842  0.092864  0.078000
26          CIFAR10_3  0.503877  0.097820  0.091255

### 23. model_23

In [ ]:
model_23_aucroc_scores = []
model_23_aucpr_scores = []
model_23_f1_scores = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_23_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_23_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_23_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_23_f1_scores.append(f1)

# compute average scores of all datasets
model_23_avg_aucroc = sum(model_23_aucroc_scores) / len(model_23_aucroc_scores)
model_23_avg_aucpr = sum(model_23_aucpr_scores) / len(model_23_aucpr_scores)
model_23_avg_f1 = sum(model_23_f1_scores) / len(model_23_f1_scores)

print(f"number of datasets: {len(model_23_aucroc_scores)}")
print(f"Average aucroc: {model_23_avg_aucroc}")
print(f"Average aucpr: {model_23_avg_aucpr}")
print(f"Average f1: {model_23_avg_f1}")

### 24.2

In [4]:
model_24_2_aucroc_scores = []
model_24_2_aucpr_scores = []
model_24_2_f1_scores = []
datasets_name = []
# walk through all folders and find result.csv files
for subdir, _, files in os.walk(model_24_2_dir):
    if "result.csv" in files:
        file_path = os.path.join(subdir, "result.csv")
        df = pd.read_csv(file_path)
        # extract dataset name
        dataset_name = os.path.basename(os.path.dirname(subdir))
        datasets_name.append(dataset_name)

        # extract scores
        aucroc = df['aucroc'].values[0]
        model_24_2_aucroc_scores.append(aucroc)

        aucpr = df['aucpr'].values[0]
        model_24_2_aucpr_scores.append(aucpr)

        f1 = df['f1'].values[0]
        model_24_2_f1_scores.append(f1)

# compute average scores of all datasets
model_24_2_avg_aucroc = sum(model_24_2_aucroc_scores) / len(model_24_2_aucroc_scores)
model_24_2_avg_aucpr = sum(model_24_2_aucpr_scores) / len(model_24_2_aucpr_scores)
model_24_2_avg_f1 = sum(model_24_2_f1_scores) / len(model_24_2_f1_scores)

print(f"number of datasets: {len(model_24_2_aucroc_scores)}")
print(f"Average aucroc: {model_24_2_avg_aucroc}")
print(f"Average aucpr: {model_24_2_avg_aucpr}")
print(f"Average f1: {model_24_2_avg_f1}")

number of datasets: 121
Average aucroc: 0.6715343906333984
Average aucpr: 0.37350591936421795
Average f1: 0.36466644923887176

In [6]:
# Analyzing top 10 Datasets with the worst aucroc scores
model_21_dict = {'dataset': datasets_name, 'aucroc': model_24_2_aucroc_scores, 'aucpr': model_24_2_aucpr_scores, 'f1': model_24_2_f1_scores}
model_21_df = pd.DataFrame(model_21_dict)
model_21_top10_best_aucroc = model_21_df.sort_values(by='aucroc', ascending=True).head(10)
model_21_top10_best_aucroc

            dataset    aucroc     aucpr        f1
5    MNIST-C_stripe  0.334639  0.098133  0.104000
41   FashionMNIST_6  0.360462  0.074611  0.082540
18   FashionMNIST_0  0.361170  0.088128  0.092063
21      MNIST-C_fog  0.370485  0.086489  0.082000
1            SVHN_5  0.374230  0.071661  0.038674
94   FashionMNIST_4  0.379277  0.077583  0.073016
106  FashionMNIST_2  0.394134  0.072815  0.041270
19   17_InternetAds  0.402205  0.365398  0.274457
26        CIFAR10_3  0.403264  0.076286  0.030418
77         24_mnist  0.409087  0.131069  0.050000

### Visualization

In [18]:
models = ['default', 'model_1', 'model_2', 'model_3', 'model_4', 'model_5', 'model_6', 'model_7', 'model_8', 'model_9', 'model_10', 'model_11', 'model_12', 'model_13']
avg_aucroc_scores = [round(default_avg_aucroc, 3), round(model_1_avg_aucroc, 3), round(model_2_avg_aucroc, 3), round(model_3_avg_aucroc, 3), round(model_4_avg_aucroc, 3), round(model_5_avg_aucroc, 3), round(model_6_avg_aucroc, 3), round(model_7_avg_aucroc, 3), round(model_8_avg_aucroc, 3), round(model_9_avg_aucroc, 3), round(model_10_avg_aucroc, 3), round(model_11_avg_aucroc, 3), round(model_12_avg_aucroc, 3), round(model_13_avg_aucroc, 3)]
avg_aucpr_scores = [round(default_avg_aucpr, 3), round(model_1_avg_aucpr, 3), round(model_2_avg_aucpr, 3), round(model_3_avg_aucpr, 3), round(model_4_avg_aucpr, 3), round(model_5_avg_aucpr, 3), round(model_6_avg_aucpr, 3), round(model_7_avg_aucpr, 3), round(model_8_avg_aucpr, 3), round(model_9_avg_aucpr, 3), round(model_10_avg_aucpr, 3), round(model_11_avg_aucpr, 3), round(model_12_avg_aucpr, 3), round(model_13_avg_aucpr, 3)]
avg_f1_scores = [round(default_avg_f1, 3), round(model_1_avg_f1, 3), round(model_2_avg_f1, 3), round(model_3_avg_f1, 3), round(model_4_avg_f1, 3), round(model_5_avg_f1, 3), round(model_6_avg_f1, 3), round(model_7_avg_f1, 3), round(model_8_avg_f1, 3), round(model_9_avg_f1, 3), round(model_10_avg_f1, 3), round(model_11_avg_f1, 3), round(model_12_avg_f1, 3), round(model_13_avg_f1, 3)]

summary_dict = {'models': models, 'average_aucroc': avg_aucroc_scores, 'average_aucpr': avg_aucpr_scores, 'average_f1': avg_f1_scores}

In [19]:
summary_results = pd.DataFrame(summary_dict)

In [20]:
summary_results

      models  average_aucroc  average_aucpr  average_f1
0    default           0.759          0.479       0.467
1    model_1           0.701          0.401       0.392
2    model_2           0.719          0.425       0.416
3    model_3           0.725          0.434       0.416
4    model_4           0.722          0.428       0.411
5    model_5           0.722          0.427       0.415
6    model_6           0.730          0.438       0.429
7    model_7           0.744          0.444       0.431
8    model_8           0.724          0.438       0.426
9    model_9           0.751          0.457       0.444
10  model_10           0.714          0.413       0.403
11  model_11           0.726          0.437       0.424
12  model_12           0.725          0.435       0.420
13  model_13           0.713          0.438       0.427